baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[menus]
    [[menus.main]]
        name="Home"
        pageRef="/"
        weight=1
    [[menus.main]]
        name="About"
        pageRef="/"
        weight=2
    [[menus.main]]
        weight=3
        name="contact us"
        pageRef="/"